### ISSUE TITLE
No way to download the Ehcache Remote Debugger

### ISSUE THREAD

**Issue by Selaron** [ehcache/ehcache.org-site#163]
There is no way to download the Ehcache Remote Debugger on the site which is mentioned in documentations:

https://www.ehcache.org/generated/2.9.0/html/ehc-all/index.html#page/Ehcache_Documentation_Set/co-rmi_about_the_remote_debugger.html

**Comment by chrisdennis** [comment]
I can fairly confidently state that this is no longer supported. I can try to track down the original files and fix up the links but it may take some time. In the meantime I believe the jar you are looking for is available on Maven central here: https://repo1.maven.org/maven2/net/sf/ehcache/ehcache-debugger/1.7.1/
