### ISSUE TITLE
Missing links in Ehcache 3 documentation

### ISSUE THREAD

**Issue by ljacomet** [ehcache/ehcache.org-site#25]
Looks like some syncing needs to happen between the asciidoc generated table and the one existing on the website. I am guessing we have duplication here ... not sure if that can be removed ... but at least needs to be in sync.

See http://www.ehcache.org/documentation/3.0/

**Comment by jhouserizer** [comment]
Yes there is duplication.  Not sure there's an easy way to resolve that.

**Comment by ljacomet** [comment]
Opened #46 for the enhancement and closing this as it was fixed during the 3.0.0 release of Ehcache.
