### ISSUE TITLE
Add a "Talks" and "Resources" section

### ISSUE THREAD

**Issue by mathieucarbou** [ehcache/ehcache.org-site#35]
In the documentation section, we could add a "Talk" section with the following links:

Bringing javax.cache'ing to your application
 * Video: https://spring.io/blog/2015/10/19/springone2gx-2015-replay-bringing-javax-cache-ing-to-your-application
* Slides: http://www.slideshare.net/SpringCentral/bringing-javaxcacheing-to-your-app

Terracotta's OffHeap Explained
* Video: https://www.youtube.com/watch?v=xCojSZMp_Zw&index=1&list=FLIxdXH5lS08edKfvRIBe-ZQ
* Slides: http://www.slideshare.net/ChrisDennis7/terracottas-offheap-explained-55214150

Ehcache 3: JSR-107 on steroids
* Slides: http://www.slideshare.net/LouisJacomet/ehcache-3-jsr107-on-steroids-at-devoxx-morocco

There are the ones I know but I guess there are plenty other ones :-)

**Comment by ljacomet** [comment]
@mathieucarbou As I commented in your PR, we already have that information in the events section.

I do not think we should duplicate it, but clearly have a link to events from the main documentation page seems an improvement.

Makes sense?

**Comment by mathieucarbou** [comment]
Yes @ljacomet ! Just adding these links in the event section would be sufficient. The idea behind that is to have a place where we can point to talks AND blog posts. That's why I added the word "resources" Currently I did not see any place where we could point to external resources talking about Ehcache.

**Comment by mathieucarbou** [comment]
Renamed the title just to match what I wanted to do ;-)

**Comment by mathieucarbou** [comment]
Replaced by #49
