### ISSUE TITLE
Clustered doc references `images/storagePools.png`: 404

### ISSUE THREAD

**Issue by alexsnaps** [ehcache/ehcache.org-site#74]
... looks like this isn't there...

**Comment by jhouserizer** [comment]
We blame some guy named Alex for mistakes like that.

(I'll try to take care of fixing it a bit later today).

**Comment by jhouserizer** [comment]
Looks like this problem slipped by due to case-insensitivity on people's machines that did testing/review  (but the webserver itself is case sensitive).

**Comment by alexsnaps** [comment]
Well thanks for fixing it @jhouserizer! No thanks to this "Alex guy" though...
