### ISSUE TITLE
Link to docs from Ehcache 3 Quick Start (on home page) is probably wrong

### ISSUE THREAD

**Issue by jhouserizer** [ehcache/ehcache.org-site#81]
Under "Not quite ready yet?" - it links directly to ehcache 3.0 docs.  Probably at this point it should link to 3.1.x docs.   Maybe for long-term "fool-proofness" it should just link to the root docs page.

**Comment by ljacomet** [comment]
I'll try something. I would like to be able to use the information in the `_config.yml` where we effectively indicate which version is the current one. Based on that we should be able to generate the link properly to the latest version of the doc without needing to change more than the `_config.yml` when releasing a new `major.minor`.
